config/routes.rb
Pictrgur::Application.routes.draw do
  
  resources :pictures
  root :to => "pictures#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base

	scope :random, -> { order("Random()").first }
	# scope :most_recent, -> { newest_first.first }
	# scope :created_before, ->(time) { where("created_at < ?", time) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @picture = Picture.random
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def show_all
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to picture_url(@picture[:id])
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(picture_params)
      redirect_to pictures_path(:id)
    else
      render :update
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

  private

  def picture_params
    params.require(:picture).permit(:artist, :title, :url) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictrgur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<%= form_for @picture do |f| %>
	<%= f.label "title" %>
	<%= f.text_field "title" %><br>

	<%= f.label "artist" %>
	<%= f.text_field "artist" %><br>

	<%= f.label :name, "URL" %>
	<%= f.text_field "url" %><br>

	<%= f.submit "SUBMIT" %>
<% end %>

app/views/pictures/find.html.erb
<h1>Pictures#find</h1>
<p>Find me in app/views/pictures/find.html.erb</p>

app/views/pictures/index.html.erb
<%= image_tag(@picture[:url]) %>
<%= link_to "ADD PICTURE", new_picture_url %>

app/views/pictures/new.html.erb
<%= form_for @picture do |form| %>
	<%= form.label "title" %>
	<%= form.text_field "title" %><br>

	<%= form.label "artist" %>
	<%= form.text_field "artist" %><br>

	<%= form.label :name, "URL" %>
	<%= form.text_field "url" %><br>

	<%= form.submit "SUBMIT" %>
<% end %>

app/views/pictures/show.html.erb
<%= image_tag(@picture[:url]) %>
<%= link_to "HOME", pictures_path %>
<%= link_to "ADD PICTURE", new_picture_url %>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>